### ISSUE TITLE
Split up and rearrange files

### ISSUE THREAD

**Issue by simonbyrne** [JuliaIO/HDF5.jl#945]
The main HDF5.jl file is rather large, and very difficult to navigate, especially since the API is not yet fully documented. I think this would be easier to develop and maintain if we were to split this up into smaller files. I originally tried this in #833, but it was quite a big change, so instead I decided to tackle it smaller chunks.

The question is what should go where. @mkitti suggested I write it up as an issue so that it can be discussed in one place.

My overall idea is to split it out according to the how the C API is broken up
- [X] Properties (`h5p`): done in #847
- [x] File functions (`h5f`): `File` type and `h5open`: #970
- [x] Group functions (`h5g`): `Group` type and `setindex!`/`getindex` overloads: #971
- [x] Datatype (`h5t`): `Datatype` and conversions between Julia types and HDF5 datatypes (#975)
- [x] Dataspace (`h5s`): `Dataspace` and conversions between Julia indexing and dataspaces: See #961
- [x] Dataset (`h5d`):  `Dataset` and `read`/`write` functionality: see #955.
- [x] Attributes (`h5a`): See #943
- [x] References (`h5r`): `Reference` type and dereferencing: see #968
- [x] Objects (`h5o`): See #976
